### ISSUE TITLE
Last Login Elapsed format outputting wrong time

### ISSUE THREAD

**Issue by nirewen** [AlessioDP/LastLoginAPI#2]
Using the placeholder %lastloginapi_last_login_elapsed% it outputs a different value. It should be %hours%h, %minutes%m, replacing the %% placeholders, but instead it's replacing like in a SimpleDateFormat method. It's replacing s for seconds and m for minutes, but not h for hours

![image](https://user-images.githubusercontent.com/8761479/71204907-0e579300-2280-11ea-821a-b0e4d93c2904.png)

**Comment by AlessioDP** [comment]
Update your config.yml, since 1.3 the format changed ;)
