### ISSUE TITLE
Pickblock function broken in 1.7.1 (works in 1.7.0)

### ISSUE THREAD

**Issue by lerokko** [AlessioDP/LastLoginAPI#61]
When trying to do pickblock it sometimes works in creative but never in survival. In survival the game never switches the hotbar slot or pulls a block from your inventory.

My server is running Paper version git-Paper-261 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 855637f)

**Comment by AlessioDP** [comment]
What do you mean with 'pickblock'?
Can you explain how to replicate it? The plugin only handles login and logout events, nothing related to inventory.

**Comment by lerokko** [comment]
Yeah my bad. I was confused by this as well, turn out its my mistake. Your plugin ha nothing todo with this.
