### ISSUE TITLE
Unrelocated SnakeYaml inside plugin jar

### ISSUE THREAD

**Issue by A248** [AlessioDP/LastLoginAPI#80]
A copy of SnakeYaml exists unrelocated in the LastLongAPI plugin jar. If I download and unzip the jar published to SpigotMC, I find classes inside `org/yaml/snakeyaml`.

I was debugging a different library issue and happened across this bug while investigating.

**Comment by AlessioDP** [comment]
I already fixed the issue for my other plugins, I will fix it with the next release ;)

**Comment by AlessioDP** [comment]
Fixed with release 1.7.4
