### ISSUE TITLE
Versioned library classes are not relocated properly

### ISSUE THREAD

**Issue by A248** [AlessioDP/LastLoginAPI#81]
LastLoginAPI's runtime relocation has a flaw. It fails to properly remap versioned classes within `META-INF/versions`. The contents of the `.class` file are relocated, but the class file is not moved to the correct directory. The result is a binary name mismatch which causes a `NoClassDefFoundError` when the original, non-versioned class is requested.

For example, notice the mariadb-java-client dependency. Relocation moves classes under `org/mariadb/jdbc` to `com/alessiodp/lastloginapi/libs/mariadb/jdbc`. This works for most classes. However, the SocketHelper.class located at `META-INF/versions/11/org/mariadb/jdbc/client/SocketHelper.class` does not move. The *contents* of the class file change; the bytecode is modified correctly and the binary class name is rewritten to com.alessiodp.lastloginapi.libs.mariadb.jdbc.client.SocketHelper. Yet the class file itself is not moved to the correct location.

Although your runtime relocation modifies the bytecode of each `.class` file correctly, it fails to move versioned classes under `META-INF/versions/` to the new location.

**Symptoms**

The result of this bug is that it breaks classloading requests for the SocketHelper class. The binary name mismatch causes a NoClassDefFoundError. This affects other plugins besides LastLoginAPI, as seen here: https://hastebin.com/lupikukici.properties

**Comment by AlessioDP** [comment]
This issue is not related to LastLoginAPI but `slimjar` > `jar-relocator`.

I see that it should be already fixed with jar-relocator v1.6-SNAPSHOT, I will release an update of the plugin as soon as those libraries get updated.

**Comment by A248** [comment]
Jar-relocator has not been formally released in over a year since the bug was fixed. I'd advise against waiting for updates of the entire dependency chain when a solution is at hand.

Since this bug causes the presence of LastLoginAPI to break other plugins, I would kindly ask you to fix the issue by depending on jar-relocator 1.6-SNAPSHOT. Until then, LastLoginAPI will adversely affect the plugin ecosystem.

**Comment by AlessioDP** [comment]
Its not a problem to use the SNAPSHOT version, I am already working on a PR for slimjar dependency, but it actually requires a lot of code changes because the source code its not getting compiled.
